import { useState, useEffect, useCallback, useRef } from 'react';

// In-memory cache for audio URLs generated by ElevenLabs narrator voice
const audioCache = new Map<string, string>();

export function useSpeech() {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [speakingText, setSpeakingText] = useState<string | null>(null);
  
  const audioElementRef = useRef<HTMLAudioElement | null>(null);

  const stop = useCallback(() => {
    // Stop HTML5 Audio if playing
    if (audioElementRef.current) {
      audioElementRef.current.pause();
      audioElementRef.current.currentTime = 0;
      audioElementRef.current = null;
    }
    setIsSpeaking(false);
    setIsLoading(false);
    setSpeakingText(null);
  }, []);

  useEffect(() => {
    return () => {
      stop();
    };
  }, [stop]);

  const playAudioDataUrl = useCallback((audioUrl: string, text: string) => {
    stop();

    const audio = new Audio(audioUrl);
    audioElementRef.current = audio;

    audio.onplay = () => {
      setIsLoading(false);
      setIsSpeaking(true);
      setSpeakingText(text);
    };

    audio.onended = () => {
      setIsSpeaking(false);
      setSpeakingText(null);
      audioElementRef.current = null;
    };

    audio.onerror = (err) => {
      console.error('ElevenLabs audio playback error:', err);
      setIsSpeaking(false);
      setIsLoading(false);
      setSpeakingText(null);
      audioElementRef.current = null;
    };

    audio.play().catch((err) => {
      console.warn('Audio play request interrupted:', err);
      setIsSpeaking(false);
      setIsLoading(false);
    });
  }, [stop]);

  const speak = useCallback(async (text: string) => {
    if (!text) return;

    // Toggle off if clicking the same currently playing text
    if (isSpeaking && speakingText === text) {
      stop();
      return;
    }

    stop();
    setIsLoading(true);
    setSpeakingText(text);

    // Check in-memory cache first
    if (audioCache.has(text)) {
      const cachedUrl = audioCache.get(text)!;
      playAudioDataUrl(cachedUrl, text);
      return;
    }

    try {
      const res = await fetch('/api/tts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });

      const json = await res.json();

      if (json.success && json.audioUrl) {
        audioCache.set(text, json.audioUrl);
        playAudioDataUrl(json.audioUrl, text);
      } else {
        setIsLoading(false);
        setSpeakingText(null);
        alert(json.error || 'Failed to generate ElevenLabs narrator audio. Please check server logs.');
      }
    } catch (err: any) {
      console.error('Error fetching ElevenLabs voice:', err);
      setIsLoading(false);
      setSpeakingText(null);
      alert('Network error requesting ElevenLabs narrator voice.');
    }
  }, [isSpeaking, speakingText, stop, playAudioDataUrl]);

  return {
    speak,
    stop,
    isSpeaking,
    isLoading,
    speakingText,
  };
}
